version: "3"

services:
  #  flask api with MongoDB
  api-events:
    image: api-events
    build:
      dockerfile: Dockerfile.dev
      context: ./unity-data-solutions
    env_file:
      - .env
    volumes:
      - ./unity-data-solutions:/app

  #  express/node api with postgres
  api-users:
    image: api-users
    build:
      dockerfile: Dockerfile.dev
      context: ./unity-api
    env_file:
      - .env
    volumes:
      - ./unity-api:/app

  #  express/node React app
  unity-hospital:
    image: unity-hospital
    build:
      dockerfile: Dockerfile.dev
      context: ./unity-hospital
    volumes:
      - ./unity-hospital:/app

  ##############################
  #  nginx server for routing
  ##############################
  nginx:
    image: nginx
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "8080:80"
