version: "3"

services:
  ##############################
  #  flask api with MongoDB
  #  nginx for production server deploy
  ##############################
  api-events:
    image: unity-data-solutions
    build:
      context: ./unity-data-solutions
      dockerfile: Dockerfile
    environment:
      FLASK_APP: "${FLASK_APP}"
      MONGO_URI: ${MONGO_URI}
    volumes:
      - "./:/unity"
  nginx:
    image: nginx-server
    build:
      context: ./unity-data-solutions
      dockerfile: Dockerfile-nginx
    depends_on:
      - api-events

  ##############################
  #  express/node api with postgres
  ##############################
  api-users:
    image: unity-api
    build: ./unity-api
    expose:
      - "${API_USERS_PORT}"
    environment:
      PG_HOST: ${PG_HOST}
      API_USERS_PORT: "${API_USERS_PORT}"
    ports:
      - "${API_USERS_PORT}:${API_USERS_PORT}"
    volumes:
      - ./unity-api/src:/unity/unity-api/src
    command: yarn start
  ##############################
  #  express/node React app
  ##############################
  web-unity:
    image: unity-hospital
    build: ./unity-hospital
    expose:
      - ${WEB_UNITY_PORT}
    environment:
      WEB_UNITY_PORT: "${WEB_UNITY_PORT}"
    ports:
      - "${WEB_UNITY_PORT}:${WEB_UNITY_PORT}"
    volumes:
      - ./unity-hospital/src:/unity/unity-hospital/src
    links:
      - api-users
      - api-events
      - nginx
    command: yarn start
