version: "3"

services:
  ##############################
  #  flask api with MongoDB
  ##############################
  api-events:
    image: api-events
    build:
      context: ./unity-data-solutions
      dockerfile: Dockerfile
    environment:
      FLASK_APP: "${FLASK_APP}"
      MONGO_URI: ${MONGO_URI}
    volumes:
      - "./:/unity"

  ##############################
  #  nginx server for routing
  ##############################
  nginx-server:
    image: nginx-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:80"

  ##############################
  #  express/node api with postgres
  ##############################
  api-users:
    image: api-users
    build: ./unity-api
    environment:
      PG_HOST: ${PG_HOST}
      API_USERS_PORT: "${API_USERS_PORT}"
    ports:
      - "${API_USERS_PORT}:${API_USERS_PORT}"
    volumes:
      - ./unity-api/src:/unity/unity-api/src

  ##############################
  #  express/node React app
  ##############################
  web-unity:
    image: unity-hospital
    build: ./unity-hospital
    environment:
      WEB_UNITY_PORT: "${WEB_UNITY_PORT}"
    ports:
      - "${WEB_UNITY_PORT}:${WEB_UNITY_PORT}"
    volumes:
      - ./unity-hospital/src:/unity/unity-hospital/src
    depends_on:
      - api-users
      - api-events
      - nginx-server
