FROM python:3.7.7

LABEL Author="Sam Jamal"
LABEL Description="image for unity-data-solutions flask app"
LABEL version="0.0.1"

WORKDIR /app

COPY requirements.txt $UNITY_DATA
RUN pip install -r requirements.txt

COPY . ./

CMD ["python", "-m", "flask", "run", "--port", "4433"]